### ISSUE TITLE
Add Auth Features

### ISSUE THREAD

**Issue by JohannCastillo** [Arctic-Cuyes/ZonaHub#28]

**Comment by Hiroshi85** [comment]
Se crea de nuevo error de creación doble de root page cuando se inicia sesión por primera vez

**Comment by Hiroshi85** [comment]
Ya lo arregle, en un momento lo subo

**Comment by Hiroshi85** [comment]
Aún no está arreglado

**Comment by Hiroshi85** [comment]
Es un error relacionado a mi parte, ahora veo como arreglarlo

**Comment by Parms221** [comment]
Tengo fe
